[unstable]
codegen-backend = true

[build]
rustflags = ["-Z", "threads=12"]

# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[profile.bindev]
codegen-backend = "cranelift"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"
# rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-unknown-linux-gnu-gcc"
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
